---
- name: Confirm local debs present if required
  hosts: localhost
  gather_facts: no
  vars:
    molecule_dir: "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}"
  tasks:
      # Before running apt-server logic, confirm we have local
      # debs built.
    - name: Establish QA strategy
      set_fact:
        QA_APTTEST: "{{ lookup('env','QA_APTTEST')|bool }}"

    - name: Find local deb files
      find:
        paths: "{{ molecule_dir }}/../../build/"
        patterns: "*.deb"
      register: _upgrade_scenario_find_debs_result
      when: not QA_APTTEST

    - name: Ensure debs were found
      assert:
        that:
          - "_upgrade_scenario_find_debs_result.files|length >= 8"
        msg: "No local debs found, run 'make build-debs'"
      when: not QA_APTTEST

- name: Re-run original tor role
  hosts: securedrop
  max_fail_percentage: 0
  any_errors_fatal: yes
  pre_tasks:
    - name: Fix hosts file
      lineinfile:
        path: /etc/hosts
        line: "{{ item.line }}"
        regexp: "{{ item.reg }}"
      with_items: "{{ etc_hosts[ansible_hostname] }}"
      tags: hosts
  roles:
    - role: tor-hidden-services
      tags: tor
    - role: restrict-direct-access
      tags: firewall
    - role: ossec
      tags: ossec
  post_tasks:
    - name: Make sure worker directory is created?
      file:
        state: directory
        path: "/var/log/{{ item }}"
      with_items:
        - securedrop_worker
        - cron-apt
    - import_tasks: reboot_and_wait.yml
      tags: reboot
  become: yes

- name: Re-run OSSEC role
  hosts: securedrop
  max_fail_percentage: 0
  any_errors_fatal: yes
  roles:
    - role: ossec
      tags: ossec
  post_tasks:
    - name: Ensure tor is running
      service:
        name: tor
        state: started
        enabled: yes
      tags: always

    - name: Ensure supervisor is running
      service:
        name: supervisor
        state: started
      delegate_to: app-staging
      runonce: yes
      tags: always
  become: yes


- import_playbook: apt.yml
  tags: apt

- name: Spit out details
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Spit out tor details
      debug:
        msg: "Source interface available at {{ lookup('file', molecule_ephemeral_directory+'/sd-orig/'+source_ths_path) }}"
      tags:
        - onion
        - always
  vars:
    molecule_ephemeral_directory: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}"
    source_ths_path: /install_files/ansible-base/app-source-ths
